### ISSUE TITLE
Speed up extract_metric function

### ISSUE THREAD

**Issue by TMondain** [BiologicalRecordsCentre/DECIDE_adaptivesampling#5]
The extract_metric() function is very slow meaning we won't be able to use it as it currently is in the app. I think the specific section that is slow is the st_join() snippet here:

https://github.com/BiologicalRecordsCentre/DECIDE_adaptivesampling/blob/458bc3676e64d0c552e93331cca8ab642507be52/Scripts/modules/extract_metric.R#L51-L54

Need to work out whether we can change the code to make it work or it's just a non-starter.

**Comment by AugustT** [comment]
Thanks @TMondain Is the repo up-to-date for me to pull down into my data lab notebook?

**Comment by TMondain** [comment]
@AugustT No worries at all, the adaptive sampling one is up-to-date but the constraint layers one isn't at the moment because I'm having issues with DataLabs. I'll let you know when it is!

**Comment by AugustT** [comment]
@TMondain Where is this called in the markdown document?

**Comment by AugustT** [comment]
is this issue closed?

**Comment by TMondain** [comment]
No, this is a function that we decided not to use in the end. It's the one that pulls the decide metric into sf objects so that we can colour e.g. a footpath by the decide score that overlaps it.

i.e. like this 
![image](https://user-images.githubusercontent.com/68549001/127466210-af1f0628-6a37-4e79-ac00-3ce0e45af9e4.png)

**Comment by AugustT** [comment]
Ah, yeah, okay. I think we can close the issue as this is a functionality we have decided we are not going to take forward
