### ISSUE TITLE
The curse of absolute paths

### ISSUE THREAD

**Issue by AugustT** [BiologicalRecordsCentre/DECIDE_adaptivesampling#6]
The code currently has a lot of absolute paths which means that the code will only work on @TMondain 's data lab. e.g. `/data/notebooks/rstudio-adaptsampthomas/DECIDE_adaptivesampling/Scripts/modules/extract_metric.R`

This can be easily fixed by changing these to relative paths. In .rmd files these need to be relative to the .rmd file. For everything else they are realtive to the .rproj file, which is at the root.

In this case it would be `Scripts/modules/extract_metric.R`

**Comment by AugustT** [comment]
https://github.com/BiologicalRecordsCentre/DECIDE_adaptivesampling/search?q=%22%2Fdata%2Fnotebooks%2Frstudio%22&type=

This should show you where edits are needed

**Comment by TMondain** [comment]
Sorry!!!

I can sort that out as it's a pain...

**Comment by AugustT** [comment]
Wait for my PR, i have fixed some, you can address what is left

**Comment by TMondain** [comment]
Okay, sounds good (sorry)

**Comment by AugustT** [comment]
Okay PR is in

**Comment by TMondain** [comment]
@AugustT I think I have changed all the absolute file paths to things other than data. I guess I'll need to move the data to a common directory later so that it's easier to navigate but I would like to wait until we have the APIs set up and running on DataLabs before moving files around...
